-Removed obsolete medm -Fixed VDCT build system and script paths -Modified epicsenv to adapt to the new location for vdct
git-svn-id: file:///afs/slac/g/pcds/vol2/svn/pcds/epics/trunk@183 ececa60f-9f63-0410-97c7-ea05888eb260

diff --git a/extensions/src/vdct/src/vdct b/extensions/src/vdct/src/vdct
--- a/extensions/src/vdct/src/vdct
+++ b/extensions/src/vdct/src/vdct
@@ -1,3 +1,8 @@
 #!/bin/sh
-
-java -cp $(dirname $0)/../lib/VisualDCT.jar com.cosylab.vdct.VisualDCT
+if [ -z "${VDCT_CLASSPATH}" ]; then
+	echo "ERROR: VDCT environment is not configured"
+	echo "This may be because you forgot to run epicsenv.sh"
+	echo "or because VDCT java files could not be found."
+	exit 1
+fi
+java -cp ${VDCT_CLASSPATH} com.cosylab.vdct.VisualDCT
